owner: shjang@reversemountain.co.kr
created_at: '2026-01-26'
current_version: v1.0
versions:
  v1.0:
    date: '2026-01-26'
    author: shjang@reversemountain.co.kr
    changes: Initial version
    langsmith_hash: null
last_pushed_hash: 78aeccb49b98c0cf
