owner: shjang@reversemountain.co.kr
created_at: '2026-02-05'
current_version: v1.1
versions:
  v1.0:
    date: '2026-02-05'
    author: shjang@reversemountain.co.kr
    changes: Initial version
    langsmith_hash: null
    langfuse_version: null
  v1.1:
    date: '2026-02-05'
    author: shjang@reversemountain.co.kr
    changes: 없음
    langsmith_hash: null
    langfuse_version: 1
last_pushed_hash: e2ed1f71b7658c2f
