# Config 스키마 정의
# 각 프롬프트 평가 설정 파일이 따라야 할 구조

# =============================================================================
# 필수 필드
# =============================================================================

name:
  type: string
  required: true
  description: 프롬프트 이름 (폴더명과 일치해야 함)
  example: prep_generate

output_format:
  type: string
  required: true
  enum: [text, json]
  description: 프롬프트 출력 형식

evaluators:
  type: array
  required: true
  description: 평가자 목록
  items:
    - type: rule_based
      checks:
        - keyword_inclusion
        - forbidden_word_check
    - type: llm_judge
      enabled: boolean
      criteria: [string]  # 'domain/name' 전체 경로 (예: oneonone/professional_tone)

# =============================================================================
# 선택 필드
# =============================================================================

description:
  type: string
  required: false
  description: 프롬프트 설명

thresholds:
  type: object
  required: false
  default:
    pass_rate: 0.85
    min_score: 0.70
  properties:
    pass_rate:
      type: number
      description: 전체 케이스 중 통과해야 할 비율
    min_score:
      type: number
      description: 개별 케이스 최소 점수

run_mode:
  type: string
  required: false
  enum: [quick, full]
  default: full
  description: |
    quick: Rule-based만 실행
    full: Rule-based + LLM Judge

prompt_file:
  type: string
  required: false
  description: |
    프롬프트 파일 직접 경로 (프로젝트 루트 기준 상대 경로).
    지정 시 targets/{name}/prompt.* 대신 해당 파일을 사용합니다.
    지원 확장자: .txt, .md, .py, .xml
  example: src/prompts/prep_output_analyze.py

prompt_key:
  type: string
  required: false
  description: |
    .py 파일에서 특정 프롬프트 변수만 선택 (예: SYSTEM_PROMPT).
    prompt_file과 함께 사용. 미지정 시 모든 *_PROMPT 변수를 로드합니다.
  example: SYSTEM_PROMPT

# =============================================================================
# 예시 config
# =============================================================================
#
# name: prep_generate
# description: 1on1 Prep Report 생성 프롬프트
# output_format: text
#
# evaluators:
#   - type: rule_based
#     checks:
#       - keyword_inclusion
#       - forbidden_word_check
#
#   - type: llm_judge
#     enabled: true
#     criteria:
#       - general/instruction_following
#       - oneonone/output_quality
#
# thresholds:
#   pass_rate: 0.85
#   min_score: 0.70
#
# run_mode: full
